<?php
declare (strict_types=1);

require_once 'ConfigWriter.php';
require_once 'SafeTempFile.php';

$hostname = explode('.', $fqdn, 2)[0];

class OpenDKIMWriter extends ConfigWriter {
    private SafeTempFile $keyTable;
    private SafeTempFile $signingTable;
    private SafeTempFile $trustedHosts;

    public function __construct() {
        parent::__construct('/etc/opendkim.conf', 0600, 'opendkim');
    }

    protected function writeHeader(SafeTempFile $fh, ?TLSConfig $defaultConfig): void {
        $this->keyTable = new SafeTempFile('/etc/opendkim/key.table', $this->mode, $this->chown);
        $this->signingTable = new SafeTempFile('/etc/opendkim/signing.table', $this->mode, $this->chown);
        $this->trustedHosts = new SafeTempFile('/etc/opendkim/trusted.hosts', $this->mode, $this->chown);

        $fh->writeLine('# This file is auto-generated by froxlor-system. Do not edit manually.');

        $fh->writeLine('# FIXED HEADER #');
        $fh->writeLine('Syslog yes');
        $fh->writeLine('SyslogSuccess yes');
        $fh->writeLine('Canonicalization relaxed/simple');
        $fh->writeLine('OversignHeaders From');
        $fh->writeLine('UserID opendkim');
        $fh->writeLine('UMask 007');
        $fh->writeLine('Socket local:/var/spool/postfix/run/opendkim/opendkim.sock');
        $fh->writeLine('PidFile /run/opendkim/opendkim.pid');
        $fh->writeLine('TrustAnchorFile /usr/share/dns/root.key');

        $fh->writeLine('Mode sv');
        $fh->writeLine('SubDomains no');

        $fh->writeLine('KeyTable /etc/opendkim/key.table');
        $fh->writeLine('SigningTable refile:/etc/opendkim/signing.table');
        $fh->writeLine('ExternalIgnoreList refile:/etc/opendkim/trusted.hosts');
        $fh->writeLine('InternalHosts refile:/etc/opendkim/trusted.hosts');

        $fh->writeLine('# PER DOMAIN CONFIGS #');

        $this->trustedHosts->writeLine('127.0.0.1');
        $this->trustedHosts->writeLine('::1');
    }

    protected function writeConfigDomain(SafeTempFile $fh, TLSConfig $config, string $domain): void {
        global $hostname;
        $fh->writeLine("Domain $domain");
        $fh->writeLine('RequireSafeKeys yes');

        $selectorFqdn = "$hostname._domainkey.$domain";
        $keyDir = "/etc/opendkim/keys/$domain";
        $keyFile = "$keyDir/$hostname.private";
        if (!file_exists($keyFile)) {
            echo "Generating OpenDKIM key for $domain" . PHP_EOL;
            verboseRun("sudo -u opendkim /bin/bash -c 'mkdir -p $keyDir && chmod 700 $keyDir && opendkim-genkey -b 2048 -d $domain -s $hostname -D $keyDir && chmod 600 $keyFile'");
        } else {
            echo "OpenDKIM key for $domain already exists, skipping generation" . PHP_EOL;
        }

        $this->keyTable->writeLine("$selectorFqdn $domain:$hostname:$keyFile");
        $this->signingTable->writeLine("*@$domain $selectorFqdn");
        $this->trustedHosts->writeLine($domain);
    }

    protected function postSave(?TLSConfig $defaultConfig): void {
        $this->keyTable->save();
        $this->signingTable->save();
        $this->trustedHosts->save();
        verboseRun('systemctl reload opendkim');
    }
}
